from selenium.webdriver.common.by import By

class AutorizationLoginLocators:
    LOCATOR_WORD_LOGIN = (By.XPATH, "//div[@id='t-btn-tab-login']")
    LOCATOR_FIELD_LOGIN = (By.XPATH, "//input[@id='username']")
    LOCATOR_LOGIN_PASSWORD = (By.XPATH, "//input[@id='password']")
    LOCATOR_WORD_FIELD_LOGIN = (By.XPATH, "//span[contains(text(),'Логин')]")
    LOCATOR_LOGIN_BUTTON_REMEMBER_ME = (By.XPATH, "//span[@class='rt-checkbox__shape rt-checkbox__shape--circular rt-checkbox__shape--orange']")
    LOCATOR_LOGIN_BUTTON_TO_COME_IN = (By.XPATH, "//button[@id='kc-login']")
    LOCATOR_YOUR_LOGIN_WHEN_REGISTERING = (By.XPATH, "//span[contains(text(),'Введите логин, указанный при регистрации')]")
    LOCATOR_LOGIN_WRONG_LOGIN_OR_PASSWORD = (By.XPATH, "//span[@id='form-error-message']")

class AutorizationMAILLocators:
    LOCATOR_WORD_MAIL = (By.XPATH, "//div[@id='t-btn-tab-mail']")
    LOCATOR_EMAIL_MAIL = (By.XPATH, "//input[@id='username']")
    LOCATOR_MAIL_PASSWORD = (By.XPATH, "//input[@id='password']")
    LOCATOR_WORD_EMAIL_MAIL = (By.XPATH, "//span[contains(text(),'Электронная почта')]")
    LOCATOR_MAIL_BUTTON_REMEMBER_ME = (By.XPATH, "//span[@class='rt-checkbox__shape rt-checkbox__shape--circular rt-checkbox__shape--orange']")
    LOCATOR_MAIL_BUTTON_TO_COME_IN = (By.XPATH, "//button[@id='kc-login']")
    LOCATOR_MAIL_WRONG_LOGIN_OR_PASSWORD = (By.XPATH, "//span[@id='form-error-message']")

class AutorizationLocators:
    LOCATOR_WORD_PHONE = (By.XPATH, "//div[@id='t-btn-tab-phone']")
    LOCATOR_NUMBER_PHONE = (By.XPATH, "//input[@id='username']")
    LOCATOR_EMAIL_PASSWORD = (By.XPATH, "//input[@id='password']")
    LOCATOR_BUTTON_REMEMBER_ME = (By.XPATH, "//span[@class='rt-checkbox__shape rt-checkbox__shape--circular rt-checkbox__shape--orange']")
    LOCATOR_BUTTON_TO_COME_IN = (By.XPATH, "//button[@id='kc-login']")
    LOCATOR_INVALID_PHONE_FORMAT = (By.XPATH, "//span[contains(text(),'Неверный формат телефона')]")
    LOCATOR_WRONG_LOGIN_OR_PASSWORD = (By.XPATH, "//span[@id='form-error-message']")
    LOCATOR_FORGOT_PASSWORD = (By.XPATH, "//a[@id='forgot_password']")
    LOCATOR_BUTTON_COME_BACK = (By.XPATH, "//button[@id='reset-back']")

class TemporaryCodeLocators:
    LOCATOR_WORD_PHONE_AUTHORIZATION = (By.XPATH, "//div[@id='t-btn-tab-phone']")
    LOCATOR_NUMBER_PHONE_AUTHORIZATION = (By.XPATH, "//input[@id='username']")
    LOCATOR_EMAIL_PASSWORD_AUTHORIZATION = (By.XPATH, "//input[@id='password']")
    LOCATOR_BUTTON_REMEMBER_ME_AUTHORIZATION = (By.XPATH, "//span[@class='rt-checkbox__shape rt-checkbox__shape--circular rt-checkbox__shape--orange']")
    LOCATOR_BUTTON_TO_COME_IN_AUTHORIZATION = (By.XPATH, "//button[@id='kc-login']")
    LOCATOR_PRIVATE_OFFICE = (By.XPATH, "//a[@id='lk-btn']")
    LOCATOR_PRIVATE_OFFICE_USERNAME = (By.XPATH, "//h2[@class='sc-bvFjSx iqOiiv']")
    LOCATOR_PRIVATE_OFFICE_USERNAME_LOG_OFF = (By.XPATH, "//span[contains(text(),'Выйти')]")
    LOCATOR_EMAIL_PHONE_AUTHORIZATION_CODE = (By.XPATH, "//input[@id='address']")
    LOCATOR_BUTTON_TO_GET_CODE = (By.XPATH, "//button[@id='otp_get_code']")
    LOCATOR_CHANGE_PHONE_OR_MAIL_CODE = (By.XPATH, "//button[@name='otp_back_phone']")
    LOCATOR_FORM_WORK_HINT = (By.XPATH, "//p[contains(text(),'Укажите почту или номер телефона, на которые необх')]")
    LOCATOR_BUTTON_NUMBER_1_CODE = (By.XPATH, "//input[@id='rt-code-0']")
    LOCATOR_BUTTON_NUMBER_2_CODE = (By.XPATH, "//input[@id='rt-code-1']")
    LOCATOR_BUTTON_NUMBER_3_CODE = (By.XPATH, "//input[@id='rt-code-2']")
    LOCATOR_BUTTON_NUMBER_4_CODE = (By.XPATH, "//input[@id='rt-code-3']")
    LOCATOR_BUTTON_NUMBER_5_CODE = (By.XPATH, "//input[@id='rt-code-4']")
    LOCATOR_BUTTON_NUMBER_6_CODE = (By.XPATH, "//input[@id='rt-code-5']")

class RecoveryPasswordLocators:
    LOCATOR_WORD_RECOVERY_PHONE = (By.XPATH, "//div[@id='t-btn-tab-phone']")
    LOCATOR_WORD_RECOVERY_MAIL = (By.XPATH, "//div[@id='t-btn-tab-mail']")
    LOCATOR_WORD_RECOVERY_LOGIN = (By.XPATH, "//div[@id='t-btn-tab-login']")
    LOCATOR_WORD_RECOVERY_PERSONAL_ACCOUNT = (By.XPATH, "//div[@id='t-btn-tab-ls']")
    LOCATOR_FIELD_RECOVERY_USERNAME = (By.XPATH, "//input[@id='username']")
    LOCATOR_FIELD_SYMBOLS = (By.XPATH, "//input[@id='captcha']")
    LOCATOR_RECOVERY_BUTTON_CONTINUE = (By.XPATH, "//button[@id='reset']")
    LOCATOR_RECOVERY_LINK_COME_BACK = (By.XPATH, "//button[@id='reset-back']")
    LOCATOR_RECOVERY_WRONG_LOGIN_OR_PICTURES = (By.XPATH, "//span[@id='form-error-message']")
    LOCATOR_PASSWORD_FIELD = (By.XPATH, "//input[@id='password']")
    LOCATOR_BUTTON_TO_COME_IN_RECOVERY = (By.XPATH, "//button[@id='kc-login']")
    LOCATOR_LINK_FORGOT_PASSWORD_RECOVERY = (By.XPATH, "//a[@id='forgot_password']")
    LOCATOR_WORD_AUTHORIZATION = (By.XPATH, "//h1[contains(text(),'Авторизация')]")

class YaSearchLocators:
    LOCATOR_LINK_REGISTRATION = (By.XPATH, "//a[@id='kc-register']")
    LOCATOR_NAME_REGISTRATION = (By.XPATH, "//input[@name='firstName']")
    LOCATOR_FAMILY_REGISTRATION = (By.XPATH, "//input[@name='lastName']")
    LOCATOR_FIELD_REGION_REGISTRATION = (By.XPATH, "rt-input-container rt-select__input")
    LOCATOR_REGISTRATION_LINK_COME_BACK = (By.XPATH, "//button[@id='reset-back']")
    LOCATOR_REGISTRATION_WORD_TEXT = (By.XPATH, "//h1[contains(text(),'Регистрация')]")
    LOCATOR_REGISTRATION_EMAIL_OR_PHONE = (By.XPATH, "//input[@id='address']")
    LOCATOR_PASSWORD_REGISTRATION = (By.XPATH, "//input[@id='password']")
    LOCATOR_PASSWORD_CONFIRMATION_REGISTRATION = (By.XPATH, "//input[@id='password-confirm']")
    LOCATOR_BUTTON_REGISTER = (By.XPATH, "//button[@name='register']")
    LOCATOR_REGISTRATION_ACCOUNT_EXISTS = (By.XPATH, "//h2[contains(text(),'Учётная запись уже существует')]")
    LOCATOR_BUTTON_LOGIN_TO_ACCOUNT = (By.XPATH, "//button[@name='gotoLogin']")
    LOCATOR_LINK_PASSWORD_RECOVERY = (By.XPATH, "//a[@id='reg-err-reset-pass']")